---
driver:
  name: vagrant
  require_chef_omnibus: '12.3.0'
  customize:
    memory: 1024
    cpus: 2
    cpuexecutioncap: 80

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
      - recipe[curl::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
      - recipe[curl::default]
    attributes:
      grafana:
        webserver_listen: ''
  - name: debian-7.4
    driver:
      box: debian-7.4.0
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.4_chef-provisionerless.box
    run_list:
      - recipe[apt::default]
      - recipe[curl::default]
  - name: centos-6.4
    driver:
      box: centos-6.4
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.4_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[grafana::default]
    attributes:
      grafana:
        http_addr: '127.0.0.1'
  - name: package
    run_list:
      - recipe[grafana::default]
    attributes:
      grafana:
        install_type: package
        http_port: 3015
  # - name: source
  #   run_list:
  #     - recipe[grafana::default]
  #   attributes:
  #     grafana:
  #       install_type: source
