AllCops:
  Exclude:
    - vendor/**/*
    - test/**/*
    - bin/**/*

AlignParameters:
  Enabled: false

LineLength:
  Max: 200

Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
