AllCops:
  Exclude:
    - vendor/**/*
    - test/**/*
    - bin/**/*

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/MethodLength:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SpaceAfterComma:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false
