AllCops:
  Exclude:
    - vendor/**/*
    - test/**/*
    - bin/**/*

AlignParameters:
  Enabled: false

LineLength:
  Max: 200

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 120

Style/AsciiComments:
  Enabled: false

Style/FileName:
  Enabled: false

Style/Next:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
