language: ruby
cache:
  bundler: true
  directories:
  - ../vendor/bundle
  - vendor/cookbooks
sudo: false
bundler_args: --without integration --path=$PWD/vendor/bundle
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
before_script:
  - bundle exec berks vendor vendor/cookbooks
script:
  - bundle exec "strainer test --except kitchen"
