language: ruby
cache:
  directories:
  - vendor/bundle
  - vendor/cookbooks
sudo: false
bundler_args: --without integration --path=$PWD/vendor/bundle
rvm:
  - 2.3
before_script:
  - bundle exec berks vendor vendor/cookbooks
script:
  - bundle exec rubocop .
  - bundle exec foodcritic --progress -f any .
  - bundle exec rspec --color --format progress
