---
# lint_and_unit: &lint_and_unit
#   - delivery
#   - danger
#   - lint-yaml
#   - lint-markdown
version: 2.1
orbs:
  kitchen: sous-chefs/kitchen@2
workflows:
  kitchen:
    jobs:
    #   - kitchen/yamllint:
    #       name: lint-yaml
    #   - kitchen/mdlint:
    #       name: lint-markdown
    #   - kitchen/danger:
    #       name: danger
    #       context: Danger
    #   - kitchen/delivery:
    #       name: delivery
      - kitchen/dokken-single:
          name: default-centos-7
          suite: default-centos-7
      - kitchen/dokken-single:
          name: ldap-centos-7
          suite: ldap-centos-7
      - kitchen/dokken-single:
          name: basic-centos-7
          suite: basic-centos-7
      - kitchen/dokken-single:
          name: plugins-centos-7
          suite: plugins-centos-7
        #   requires: *lint_and_unit
